### ISSUE TITLE
Github Action - Automatic platform detection not working

### ISSUE THREAD

**Issue by arthurpalves** [Backbase/variants#109]
# What

When using Variants from Github Action Marketplace, automatic platform detection isn't possible, as parameter `platform` must be specified.

# Usage

```
- uses: backbase/variants@0.9.1
  with:
    variant: test
    verbose: true
```

# Error

/Users/runner/work/_temp/b002d855-4389-4630-ab97-fcaeba0ba8e8.sh: line 6: conditional binary operator expected

# Temporary solution:

Specify platform:
```
- uses: backbase/variants@0.9.1
  with:
    platform: ios
    variant: test
    verbose: true
```
