### ISSUE TITLE
Modify syntax that supports environment variable values

### ISSUE THREAD

**Issue by FizzyMobile** [Backbase/variants#121]
The syntax for environment variables could be simplified. Introducing additional key to custom properties dictionary indicating environment variable is one option.

As a result property definition would look like this:
```
custom:
    - name: NAME_OF_PROPERTY
      value: NAME_OF_ENV_VAR
      env: true [true|false(default)]
      destination: project
```
