### ISSUE TITLE
Unable to install Variants v1.1.0 through Github Marketplace action

### ISSUE THREAD

**Issue by vaibhavmBB** [Backbase/variants#189]
Following installs an older version of Variant instead of expected v1.1.0.

```
    - uses: backbase/variants@1.1.0
      with:
        platform: ios
        variant: ${{ inputs.ENVIRONMENT }}
        verbose: true
```
