### ISSUE TITLE
Allow free choice of different display name as per the custom variant

### ISSUE THREAD

**Issue by dileepZion** [Backbase/variants#237]
## Background

- If it is an enhancement of an existing feature, describe which feature and how it works at the moment.
- Currently the V_APP_NAME as per the tool, works to change the Bundle name(Target name) and also the Bundle Display name.
Hence it is not possible to use only V_APP_NAME or app_name as a parameter to switch to different names of the app.
Currently when I have gone through the code, here is the below way to update the info.plist
In XCConfigFactory, updateInfoPlist method has below code:
```
Bash("plutil", arguments: "-replace", "CFBundleName", "-string", "$(V_APP_NAME)", configFilePath),
Bash("plutil", arguments: "-replace", "CFBundleDisplayName", "-string", "$(V_APP_NAME)", configFilePath),
Bash("plutil", arguments: "-replace", "CFBundleExecutable", "-string", "$(V_APP_NAME)", configFilePath),
```

## Solution
It is good if we only give the V_APP_NAME to CFBundleName and CFBundleExecutable and allow the user to change CFBundleDisplayName according to their own requirement. Like,
Dev -> APP_NAME_DEV
QA -> APP_NAME_QA
UAT -> APP_NAME_UAT

Thanks!

**Comment by GMinucci** [comment]
Hi @dileepZion , thanks for the suggestion. I was testing in the latest variants configuration and just using the app name I was able to rename my app without breaking anything. For example, the following configuration:
```yaml
#
# Auto generated by Variants
#

ios:
    xcodeproj: VariantsTestApp.xcodeproj
    target:
        name: VariantsTestApp
        bundle_id: com.backbase.VariantsTestApp
        test_target: VariantsTestAppTests
    ...
    variants:
        default:
            ...
        Beta:
            id_suffix: beta
            ...
        Prod:
            id_suffix: beta
            app_name: Variants
            ...
```
This will produce the following apps:
- Running `variants switch` will select the `default` variant and the app name will be `VariantsTestApp`
- Running `variants switch --variant beta` will select the `beta` variant and the app name will be `VariantsTestApp Beta` since you are not providing a `app_name`, meaning the name will be the base name `VariantsTestApp` combined with the variant name `Beta`
- Running `variants switch --variant prod` will select the `prod` variant and the app name will be `Variants` as it's specified in the `app_name` configuration for the variant
Does that achieve the requirement already or is there anything missing?
