### ISSUE TITLE
Improve 'init' command to automatically populate variants spec for iOS

### ISSUE THREAD

**Issue by arthurpalves** [Backbase/variants#43]
# Background

`variants init` command requires a <platform> argument:
```
Usage: variants init <platform>
```

This uses the correct template to generate a `variants.yml` spec.

# Enhancement 1

For platform `ios`, automatically populate the following fields in `variants.yml`:
```
    xcodeproj: {{ PROJECT }}.xcodeproj
    targets:
      {{ PROJECT }}:
        name: {{ PROJECT }}
        bundle_id: {{ BUNDLE_ID }}
```

# Notes

This is based on suggestion/change request #27
