### ISSUE TITLE
Add support for Environment Variables with GYB

### ISSUE THREAD

**Issue by arthurpalves** [Backbase/variants#87]
# What

Make environment variables accessible at `Variants.environment.` as static properties. Allowing us to setup API tokens or any kind of secrets that shouldn't be committed yet available to project.

# How

Especifically for `project` and platform `ios`, using [GYB](https://nshipster.com/swift-gyb/)

# Why

We often find ourselves in need to use an API token - or any other secret - in our codebase or CD setup that shouldn't, by any means, be hardcoded nor committed in the repository. It's common in these situations to use _environment variables_.

This is supported given the pattern `"{{ envVars.NAME_OF_ENV_VAR }}"`, as the following properties in `variants.yml` spec:

```yaml
custom:
    - name: NAME_OF_PROPERTY
      value: "{{ envVars.NAME_OF_ENV_VAR }}"
      destination: project
    - name: DEPLOYMENT_API_TOKEN
      value: "{{ envVars.APPCENTER_API_TOKEN }}"
      destination: fastlane
```

The above is already supported by `fastlane` destination, generating:
```
VARIANTS_PARAMS = {
    DEPLOYMENT_API_TOKEN: ENV["APPCENTER_API_TOKEN"],
}.freeze
```

And `project` whose platform is `android`:

```
// ==== Custom values ====
rootProject.ext.NAME_OF_PROPERTY = System.getenv('NAME_OF_ENV_VAR')
```
